### ISSUE TITLE
Elm static template without model and decoder

### ISSUE THREAD

**Issue by halfzebra** [eeue56/elm-static-html-lib#2]
Would it make sense to add an option to have a static template without a model and decoder?

I'm up for making a PR with the feature.

**Comment by klaftertief** [comment]
My use case would be to generate static templates with placeholder strings for the actual data, so a constant model in the Elm module is sufficient. This way I can e.g. easily share styles between a web app and transactional e-mails.

**Comment by eeue56** [comment]
Published as 0.0.9

**Comment by halfzebra** [comment]
Awesome, thanks!

**Comment by klaftertief** [comment]
Ditto 🎉
